using System;
using System.Collections.Generic;
using YamlDotNet.Core;
using YamlDotNet.Core.Events;
using YamlDotNet.RepresentationModel;

namespace PCL.Core.App.Configuration.Storage;

// Partly generated by gpt-5 (20250903)
public sealed class YamlNodeEmitter : IEmitter
{
    private readonly List<YamlDocument> _documents = [];
    private readonly Stack<Container> _stack = new();
    private readonly Dictionary<string, YamlNode> _anchors = new(StringComparer.Ordinal);
    private bool _inStream;

    public IReadOnlyList<YamlDocument> Documents => _documents;

    public YamlNode SingleRootNode => _documents.Count switch
    {
        0 => throw new InvalidOperationException("No YAML documents have been produced."),
        1 => _documents[0].RootNode,
        _ => throw new InvalidOperationException("Multiple YAML documents exist. Use Documents instead.")
    };

    public void Reset()
    {
        _documents.Clear();
        _stack.Clear();
        _anchors.Clear();
        _inStream = false;
    }

    public void Emit(ParsingEvent @event)
    {
        switch (@event)
        {
            case StreamStart:
                Reset();
                _inStream = true;
                break;

            case StreamEnd:
                _inStream = false;
                if (_stack.Count != 0)
                    throw new InvalidOperationException("The container stack was not empty at StreamEnd. The event sequence is unbalanced.");
                break;

            case DocumentStart:
                _RequireStream();
                _stack.Push(Container.Document());
                break;

            case DocumentEnd:
                {
                    _RequireStream();
                    if (_stack.Count == 0 || _stack.Peek().Kind != ContainerKind.Document)
                        throw new InvalidOperationException("DocumentEnd is missing a matching DocumentStart.");

                    var doc = _stack.Pop();
                    if (doc.Node is null)
                        throw new InvalidOperationException("The YAML document is empty because no root node was assigned.");

                    _documents.Add(new YamlDocument(doc.Node));
                }
                break;

            case MappingStart mapStart:
                {
                    var map = new YamlMappingNode();
                    _ApplyAnchor(mapStart, map);
                    _AttachToParent(map);
                    _stack.Push(Container.Mapping(map));
                }
                break;

            case MappingEnd:
                {
                    if (_stack.Count == 0 || _stack.Peek().Kind != ContainerKind.Mapping)
                        throw new InvalidOperationException("MappingEnd is missing a matching MappingStart.");

                    var finished = _stack.Pop();
                    // no-op: already attached to the parent in Start.
                    if (finished.PendingKey is not null)
                        throw new InvalidOperationException("The YAML mapping ended with a key that has no corresponding value.");
                }
                break;

            case SequenceStart seqStart:
                {
                    var seq = new YamlSequenceNode();
                    _ApplyAnchor(seqStart, seq);
                    _AttachToParent(seq);
                    _stack.Push(Container.Sequence(seq));
                }
                break;

            case SequenceEnd:
                {
                    if (_stack.Count == 0 || _stack.Peek().Kind != ContainerKind.Sequence)
                        throw new InvalidOperationException("SequenceEnd is missing a matching SequenceStart.");

                    _stack.Pop(); // already attached to the parent in Start.
                }
                break;

            case Scalar scalar:
                {
                    var node = new YamlScalarNode(scalar.Value);
                    _ApplyAnchor(scalar, node);
                    _AttachToParent(node);
                }
                break;

            case AnchorAlias alias:
                {
                    var anchorName = alias.Value.Value; // AnchorName.Value -> string
                    if (!_anchors.TryGetValue(anchorName, out var target))
                        throw new InvalidOperationException($"No definition was found for anchor '{anchorName}'.");
                    _AttachToParent(target);
                }
                break;
        }
    }

    private void _RequireStream()
    {
        if (!_inStream)
            throw new InvalidOperationException("Events must be received between StreamStart and StreamEnd.");
    }

    private void _ApplyAnchor(NodeEvent nodeEvent, YamlNode node)
    {
        // Register only when an anchor is present; Tag/Style can be extended later if needed.
        if (nodeEvent.Anchor.IsEmpty) return;
        var name = nodeEvent.Anchor.Value;
        node.Anchor = name;
        // The current YamlDotNet representation model allows the same node reference to be reused.
        // Treat duplicate anchor definitions as invalid.
        if (!_anchors.TryAdd(name, node))
            throw new InvalidOperationException($"Anchor '{name}' was defined more than once.");
    }

    private void _AttachToParent(YamlNode node)
    {
        if (_stack.Count == 0)
        {
            throw new InvalidOperationException("DocumentStart is missing, so the root node cannot be assigned to a document.");
        }

        var parent = _stack.Peek();
        switch (parent.Kind)
        {
            case ContainerKind.Document:
                if (parent.Node is not null)
                    throw new InvalidOperationException("A YAML document can contain only one root node.");
                parent.Node = node;
                _stack.Pop();
                _stack.Push(parent); // write the updated value back
                break;

            case ContainerKind.Sequence:
                ((YamlSequenceNode)parent.Node!).Add(node);
                break;

            case ContainerKind.Mapping:
                if (parent.PendingKey is null)
                {
                    parent.PendingKey = node; // as key
                }
                else
                {
                    ((YamlMappingNode)parent.Node!).Add(parent.PendingKey, node);
                    parent.PendingKey = null;
                }
                _stack.Pop();
                _stack.Push(parent); // write the updated value back
                break;

            default:
                throw new ArgumentOutOfRangeException();
        }
    }

    private enum ContainerKind { Document, Mapping, Sequence }

    private struct Container
    {
        public ContainerKind Kind;
        public YamlNode? Node;
        public YamlNode? PendingKey;

        public static Container Document() => new() { Kind = ContainerKind.Document, Node = null, PendingKey = null };
        public static Container Mapping(YamlMappingNode map) => new() { Kind = ContainerKind.Mapping, Node = map, PendingKey = null };
        public static Container Sequence(YamlSequenceNode seq) => new() { Kind = ContainerKind.Sequence, Node = seq, PendingKey = null };
    }
}
