using System.IO;
using PCL.Core.App.Essentials;
using PCL.Frontend.Spike.Cli;
using PCL.Frontend.Spike.Models;
using PCL.Frontend.Spike.Workflows;
using PCL.Frontend.Spike.Workflows.Inspection;

namespace PCL.Frontend.Spike.ViewModels;

internal sealed partial class FrontendShellViewModel
{
    private static readonly string LauncherRootDirectory = Path.GetFullPath(Path.Combine(
        AppContext.BaseDirectory,
        "..",
        "..",
        "..",
        "..",
        "Plain Craft Launcher 2"));
    private static readonly string LaunchAvatarImageFilePath = GetLauncherAssetPath("Images", "Heads", "PCL-Community.png");
    private static readonly string LaunchNewsImageFilePath = GetLauncherAssetPath("Images", "Backgrounds", "server_bg.png");
    private static readonly string UpdateAvailableIconFilePath = GetLauncherAssetPath("Images", "Heads", "Logo-CE.png");
    private static readonly string UpdateCurrentIconFilePath = GetLauncherAssetPath("Images", "icon.png");
    private static readonly string UpdateOptionalIconFilePath = GetLauncherAssetPath("Images", "Heads", "Logo-CE.png");
    private readonly FrontendShellActionService _shellActionService;
    private FrontendShellComposition _shellComposition;
    private FrontendSetupComposition _setupComposition;
    private FrontendInstanceComposition _instanceComposition;
    private FrontendSetupUpdateStatus _updateStatus = FrontendSetupUpdateStatusService.CreateDefault();
    private StartupSpikePlan _startupPlan;
    private FrontendLaunchComposition _launchComposition;
    private readonly CrashSpikePlan _crashPlan;
    private readonly Dictionary<SpikePromptLaneKind, List<PromptCardViewModel>> _promptCatalog;
    private readonly IReadOnlyList<HelpTopicViewModel> _allHelpTopics;
    private readonly List<LauncherFrontendRoute> _routeHistory = [];
    private readonly ActionCommand _backCommand;
    private readonly ActionCommand _togglePromptOverlayCommand;
    private readonly ActionCommand _dismissPromptOverlayCommand;
    private readonly ActionCommand _launchCommand;
    private readonly ActionCommand _versionSelectCommand;
    private readonly ActionCommand _versionSetupCommand;
    private readonly ActionCommand _toggleLaunchMigrationCommand;
    private readonly ActionCommand _toggleLaunchNewsCommand;
    private readonly ActionCommand _dismissLaunchCommunityHintCommand;
    private readonly ActionCommand _openFeedbackCommand;
    private readonly ActionCommand _exportLogCommand;
    private readonly ActionCommand _exportAllLogsCommand;
    private readonly ActionCommand _openLogDirectoryCommand;
    private readonly ActionCommand _cleanLogsCommand;
    private readonly ActionCommand _getMirrorCdkCommand;
    private readonly ActionCommand _downloadUpdateCommand;
    private readonly ActionCommand _showUpdateDetailCommand;
    private readonly ActionCommand _checkUpdateAgainCommand;
    private readonly ActionCommand _openFullChangelogCommand;
    private readonly ActionCommand _downloadOptionalUpdateCommand;
    private readonly ActionCommand _showOptionalUpdateDetailCommand;
    private readonly ActionCommand _resetGameLinkSettingsCommand;
    private readonly ActionCommand _resetGameManageSettingsCommand;
    private readonly ActionCommand _resetLauncherMiscSettingsCommand;
    private readonly ActionCommand _exportSettingsCommand;
    private readonly ActionCommand _importSettingsCommand;
    private readonly ActionCommand _applyProxySettingsCommand;
    private readonly ActionCommand _addJavaRuntimeCommand;
    private readonly ActionCommand _selectAutoJavaCommand;
    private readonly ActionCommand _resetUiSettingsCommand;
    private readonly ActionCommand _openSnapshotBuildCommand;
    private readonly ActionCommand _backgroundOpenFolderCommand;
    private readonly ActionCommand _backgroundRefreshCommand;
    private readonly ActionCommand _backgroundClearCommand;
    private readonly ActionCommand _musicOpenFolderCommand;
    private readonly ActionCommand _musicRefreshCommand;
    private readonly ActionCommand _musicClearCommand;
    private readonly ActionCommand _changeLogoImageCommand;
    private readonly ActionCommand _deleteLogoImageCommand;
    private readonly ActionCommand _refreshHomepageCommand;
    private readonly ActionCommand _generateHomepageTutorialFileCommand;
    private readonly ActionCommand _viewHomepageTutorialCommand;
    private readonly ActionCommand _openHomepageMarketCommand;
    private readonly ActionCommand _toggleLaunchAdvancedOptionsCommand;
    private readonly ActionCommand _acceptGameLinkTermsCommand;
    private readonly ActionCommand _testLobbyNatCommand;
    private readonly ActionCommand _loginNatayarkAccountCommand;
    private readonly ActionCommand _joinLobbyCommand;
    private readonly ActionCommand _pasteLobbyIdCommand;
    private readonly ActionCommand _clearLobbyIdCommand;
    private readonly ActionCommand _createLobbyCommand;
    private readonly ActionCommand _refreshLobbyWorldsCommand;
    private readonly ActionCommand _inputLobbyPortCommand;
    private readonly ActionCommand _copyLobbyVirtualIpCommand;
    private readonly ActionCommand _copyActiveLobbyIdCommand;
    private readonly ActionCommand _exitLobbyCommand;
    private readonly ActionCommand _openLobbyReportCommand;
    private readonly ActionCommand _openNatayarkPolicyCommand;
    private readonly ActionCommand _openLobbyPrivacyPolicyCommand;
    private readonly ActionCommand _disableGameLinkFeatureCommand;
    private readonly ActionCommand _openGameLinkFaqCommand;
    private readonly ActionCommand _openEasyTierWebsiteCommand;
    private readonly ActionCommand _openPysioWebsiteCommand;
    private readonly ActionCommand _selectDownloadFolderCommand;
    private readonly ActionCommand _startCustomDownloadCommand;
    private readonly ActionCommand _openCustomDownloadFolderCommand;
    private readonly ActionCommand _saveOfficialSkinCommand;
    private readonly ActionCommand _previewAchievementCommand;
    private readonly ActionCommand _saveAchievementCommand;
    private readonly ActionCommand _selectHeadSkinCommand;
    private readonly ActionCommand _saveHeadCommand;
    private readonly ActionCommand _resetDownloadInstallSurfaceCommand;
    private readonly ActionCommand _manageDownloadFavoriteTargetCommand;
    private readonly ActionCommand _resetInstanceExportOptionsCommand;
    private readonly ActionCommand _importInstanceExportConfigCommand;
    private readonly ActionCommand _saveInstanceExportConfigCommand;
    private readonly ActionCommand _openInstanceExportGuideCommand;
    private readonly ActionCommand _startInstanceExportCommand;
    private readonly ActionCommand _setLittleSkinCommand;
    private readonly ActionCommand _lockInstanceLoginCommand;
    private readonly ActionCommand _createInstanceProfileCommand;
    private readonly ActionCommand _openGlobalLaunchSettingsCommand;
    private LauncherFrontendRoute _currentRoute;
    private LauncherFrontendNavigationView? _currentNavigation;
    private SpikePromptLaneKind _selectedPromptLane;
    private string _eyebrow = string.Empty;
    private string _title = string.Empty;
    private string _description = string.Empty;
    private string _status = string.Empty;
    private string _breadcrumbTrail = string.Empty;
    private string _surfaceMeta = string.Empty;
    private string _promptInboxTitle = string.Empty;
    private string _promptInboxSummary = string.Empty;
    private string _promptEmptyState = string.Empty;
    private bool _canGoBack;
    private bool _isPromptOverlayOpen;
    private bool _isLaunchMigrationExpanded = true;
    private bool _isLaunchNewsExpanded = true;
    private bool _showLaunchCommunityHint = true;
    private string _helpSearchQuery = string.Empty;
    private int _selectedUpdateChannelIndex;
    private int _selectedUpdateModeIndex;
    private string _mirrorCdk = string.Empty;
    private bool _isCheckingUpdate;
    private string _lastUpdateCheckSignature = string.Empty;
    private string _linkUsername = string.Empty;
    private int _selectedProtocolPreferenceIndex;
    private bool _preferLowestLatencyPath = true;
    private bool _tryPunchSymmetricNat = true;
    private bool _allowIpv6Communication = true;
    private bool _enableLinkCliOutput;
    private string _gameLinkAnnouncement = "正在连接到大厅服务器...";
    private string _gameLinkNatStatus = "点击测试";
    private string _gameLinkAccountStatus = "点击登录 Natayark 账户";
    private string _gameLinkLobbyId = string.Empty;
    private string _gameLinkSessionPing = "-ms";
    private string _gameLinkSessionId = "尚未创建大厅";
    private string _gameLinkConnectionType = "连接中";
    private string _gameLinkConnectedUserName = "未登录";
    private string _gameLinkConnectedUserType = "大厅访客";
    private int _selectedGameLinkWorldIndex;
    private string _toolDownloadUrl = "https://example.invalid/files/demo-pack.zip";
    private string _toolDownloadUserAgent = "PCL-CE-Spike/1.0";
    private string _toolDownloadFolder = "/Users/demo/Downloads/PCL";
    private string _toolDownloadName = "demo-pack.zip";
    private string _officialSkinPlayerName = "Steve";
    private string _achievementBlockId = "diamond_sword";
    private string _achievementTitle = "Achievement Get!";
    private string _achievementFirstLine = "Time to Strike!";
    private string _achievementSecondLine = "PCL Frontend Spike";
    private bool _showAchievementPreview;
    private int _selectedHeadSizeIndex;
    private string _selectedHeadSkinPath = "尚未选择皮肤";
    private string _downloadInstallName = "新的安装方案";
    private string _downloadCatalogIntroTitle = string.Empty;
    private string _downloadCatalogIntroBody = string.Empty;
    private string _downloadFavoriteSearchQuery = string.Empty;
    private int _selectedDownloadFavoriteTargetIndex;
    private string _downloadFavoriteWarningText = string.Empty;
    private bool _showDownloadFavoriteWarning;
    private int _selectedLaunchIsolationIndex = 1;
    private string _launchWindowTitle = "{}{name} | 玩家 : {user} | 使用 {login} 登录";
    private string _launchCustomInfo = "PCL";
    private int _selectedLaunchVisibilityIndex = 4;
    private int _selectedLaunchPriorityIndex = 1;
    private int _selectedLaunchWindowTypeIndex = 1;
    private string _launchWindowWidth = "854";
    private string _launchWindowHeight = "480";
    private bool _useAutomaticRamAllocation = true;
    private double _customRamAllocation = 3;
    private bool _optimizeMemoryBeforeLaunch = true;
    private bool _isLaunchAdvancedOptionsExpanded;
    private int _selectedLaunchRendererIndex;
    private string _launchJvmArguments = "-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions";
    private string _launchGameArguments = string.Empty;
    private string _launchBeforeCommand = string.Empty;
    private bool _waitForLaunchBeforeCommand;
    private bool _disableJavaLaunchWrapper;
    private bool _disableRetroWrapper;
    private bool _requireDedicatedGpu = true;
    private bool _useJavaExecutable;
    private int _selectedLaunchMicrosoftAuthIndex;
    private int _selectedLaunchPreferredIpStackIndex;
    private int _selectedDownloadSourceIndex;
    private int _selectedVersionSourceIndex;
    private double _downloadThreadLimit = 63;
    private double _downloadSpeedLimit = 42;
    private bool _autoSelectNewInstance = true;
    private bool _upgradePartialAuthlib = true;
    private int _selectedCommunityDownloadSourceIndex = 1;
    private int _selectedFileNameFormatIndex = 1;
    private int _selectedModLocalNameStyleIndex;
    private bool _ignoreQuiltLoader;
    private bool _notifyReleaseUpdates = true;
    private bool _notifySnapshotUpdates;
    private bool _autoSwitchGameLanguageToChinese = true;
    private bool _detectClipboardResourceLinks = true;
    private int _selectedSystemActivityIndex;
    private double _animationFpsLimit = 59;
    private double _maxRealTimeLogValue = 13;
    private bool _disableHardwareAcceleration;
    private bool _enableTelemetry = true;
    private bool _isLaunchBlockedByPrompt;
    private bool _enableDoH = true;
    private int _selectedHttpProxyTypeIndex;
    private string _httpProxyAddress = string.Empty;
    private string _httpProxyUsername = string.Empty;
    private string _httpProxyPassword = string.Empty;
    private double _debugAnimationSpeed = 30;
    private bool _skipCopyDuringDownload;
    private bool _debugModeEnabled;
    private bool _debugDelayEnabled;
    private int _selectedDarkModeIndex = 2;
    private int _selectedLightColorIndex;
    private int _selectedDarkColorIndex = 1;
    private double _launcherOpacity = 360;
    private bool _showLauncherLogo = true;
    private bool _lockWindowSize;
    private bool _showLaunchingHint = true;
    private bool _enableAdvancedMaterial;
    private double _blurRadius = 14;
    private double _blurSamplingRate = 65;
    private int _selectedBlurTypeIndex;
    private int _selectedGlobalFontIndex;
    private int _selectedMotdFontIndex = 1;
    private bool _autoPauseVideo = true;
    private bool _backgroundColorful = true;
    private double _musicVolume = 680;
    private bool _musicRandomPlay = true;
    private bool _musicAutoStart;
    private bool _musicStartOnGameLaunch = true;
    private bool _musicStopOnGameLaunch;
    private bool _musicEnableSmtc = true;
    private int _selectedLogoTypeIndex = 1;
    private bool _logoAlignLeft = true;
    private string _logoText = "Plain Craft Launcher";
    private int _selectedHomepageTypeIndex = 1;
    private string _homepageUrl = "https://example.invalid/homepage.json";
    private int _selectedHomepagePresetIndex = 14;
    private string _selectedJavaRuntimeKey = "auto";
    private bool _suppressSetupPersistence;
    private bool _suppressInstancePersistence;

    public static FrontendShellViewModel CreateBootstrap(
        SpikeCommandOptions options,
        FrontendShellActionService shellActionService)
    {
        return new FrontendShellViewModel(options, shellActionService);
    }

    private FrontendShellViewModel(
        SpikeCommandOptions options,
        FrontendShellActionService shellActionService)
    {
        _shellActionService = shellActionService;
        _shellComposition = FrontendShellCompositionService.Compose(options);
        _setupComposition = FrontendSetupCompositionService.Compose(shellActionService.RuntimePaths);
        _instanceComposition = FrontendInstanceCompositionService.Compose(shellActionService.RuntimePaths);
        _startupPlan = new StartupSpikePlan(
            LauncherStartupWorkflowService.BuildPlan(_shellComposition.StartupWorkflowRequest),
            _shellComposition.StartupConsentResult);
        _launchComposition = FrontendLaunchCompositionService.Compose(options, shellActionService.RuntimePaths);
        _crashPlan = FrontendInspectionCrashCompositionService.Compose(options);
        _currentRoute = _shellComposition.NavigationRequest.CurrentRoute;
        _selectedPromptLane = SpikePromptLaneKind.Startup;
        _backCommand = new ActionCommand(NavigateBack, () => CanGoBack);
        _togglePromptOverlayCommand = new ActionCommand(TogglePromptOverlay);
        _dismissPromptOverlayCommand = new ActionCommand(() => SetPromptOverlayOpen(false));
        _launchCommand = new ActionCommand(HandleLaunchRequested);
        _versionSelectCommand = new ActionCommand(() => NavigateTo(new LauncherFrontendRoute(LauncherFrontendPageKey.InstanceSelect), "Opened instance selection from the launch pane."));
        _versionSetupCommand = new ActionCommand(() => NavigateTo(new LauncherFrontendRoute(LauncherFrontendPageKey.InstanceSetup), "Opened instance settings from the launch pane."));
        _toggleLaunchMigrationCommand = new ActionCommand(ToggleLaunchMigrationCard);
        _toggleLaunchNewsCommand = new ActionCommand(ToggleLaunchNewsCard);
        _dismissLaunchCommunityHintCommand = new ActionCommand(() => ShowLaunchCommunityHint = false);
        _openFeedbackCommand = CreateLinkCommand("打开反馈入口", "https://github.com/PCL-Community/PCL2-CE/issues");
        _exportLogCommand = new ActionCommand(() => ExportLauncherLogs(includeAllLogs: false));
        _exportAllLogsCommand = new ActionCommand(() => ExportLauncherLogs(includeAllLogs: true));
        _openLogDirectoryCommand = new ActionCommand(OpenLauncherLogDirectory);
        _cleanLogsCommand = new ActionCommand(CleanLauncherLogs);
        _getMirrorCdkCommand = CreateLinkCommand("获取 Mirror 酱 CDK", "https://mirrorchyan.com/");
        _downloadUpdateCommand = new ActionCommand(DownloadAvailableUpdate);
        _showUpdateDetailCommand = new ActionCommand(ShowAvailableUpdateDetail);
        _checkUpdateAgainCommand = new ActionCommand(() => _ = CheckForLauncherUpdatesAsync(forceRefresh: true));
        _openFullChangelogCommand = CreateLinkCommand("查看更新日志", "https://github.com/PCL-Community/PCL2-CE/releases");
        _downloadOptionalUpdateCommand = CreateIntentCommand("下载可选更新", "Would start the optional AquaCL upgrade flow.");
        _showOptionalUpdateDetailCommand = CreateIntentCommand("查看 AquaCL 更新详情", "Would open the optional upgrade changelog surface.");
        _resetGameLinkSettingsCommand = new ActionCommand(ResetGameLinkSurface);
        _resetGameManageSettingsCommand = new ActionCommand(ResetGameManageSurface);
        _resetLauncherMiscSettingsCommand = new ActionCommand(ResetLauncherMiscSurface);
        _exportSettingsCommand = new ActionCommand(ExportSettingsSnapshot);
        _importSettingsCommand = new ActionCommand(() => _ = ImportSettingsAsync());
        _applyProxySettingsCommand = new ActionCommand(ApplyProxySettings);
        _addJavaRuntimeCommand = new ActionCommand(AddJavaRuntime);
        _selectAutoJavaCommand = new ActionCommand(() => SelectJavaRuntime("auto"));
        _resetUiSettingsCommand = new ActionCommand(ResetUiSurface);
        _openSnapshotBuildCommand = CreateLinkCommand("获取官方快照版", "https://github.com/PCL-Community/PCL2-CE");
        _backgroundOpenFolderCommand = new ActionCommand(OpenBackgroundFolder);
        _backgroundRefreshCommand = new ActionCommand(RefreshBackgroundAssets);
        _backgroundClearCommand = new ActionCommand(ClearBackgroundAssets);
        _musicOpenFolderCommand = new ActionCommand(OpenMusicFolder);
        _musicRefreshCommand = new ActionCommand(RefreshMusicAssets);
        _musicClearCommand = new ActionCommand(ClearMusicAssets);
        _changeLogoImageCommand = new ActionCommand(() => _ = ChangeLogoImageAsync());
        _deleteLogoImageCommand = new ActionCommand(DeleteLogoImage);
        _refreshHomepageCommand = new ActionCommand(RefreshHomepageContent);
        _generateHomepageTutorialFileCommand = new ActionCommand(GenerateHomepageTutorialFile);
        _viewHomepageTutorialCommand = new ActionCommand(ViewHomepageTutorial);
        _openHomepageMarketCommand = CreateLinkCommand("前往主页市场", "https://pclhomeplazaoss.lingyunawa.top:26994/d/Homepages/Homepage.Market/Custom.xaml");
        _toggleLaunchAdvancedOptionsCommand = new ActionCommand(() => IsLaunchAdvancedOptionsExpanded = !IsLaunchAdvancedOptionsExpanded);
        _acceptGameLinkTermsCommand = new ActionCommand(AcceptGameLinkTerms);
        _testLobbyNatCommand = new ActionCommand(TestLobbyNat);
        _loginNatayarkAccountCommand = new ActionCommand(LoginNatayarkAccount);
        _joinLobbyCommand = new ActionCommand(JoinLobby);
        _pasteLobbyIdCommand = new ActionCommand(PasteLobbyId);
        _clearLobbyIdCommand = new ActionCommand(ClearLobbyId);
        _createLobbyCommand = new ActionCommand(CreateLobby);
        _refreshLobbyWorldsCommand = new ActionCommand(RefreshLobbyWorlds);
        _inputLobbyPortCommand = CreateIntentCommand("手动输入联机端口", "Would allow manual LAN port entry before creating the lobby.");
        _copyLobbyVirtualIpCommand = CreateIntentCommand("复制虚拟 IP", "Would copy the current EasyTier virtual IP for the active lobby.");
        _copyActiveLobbyIdCommand = new ActionCommand(() => AddActivity("复制大厅编号", string.IsNullOrWhiteSpace(GameLinkSessionId) ? "尚未生成大厅编号。" : GameLinkSessionId));
        _exitLobbyCommand = new ActionCommand(ExitLobby);
        _openLobbyReportCommand = CreateLinkCommand("违法违规举报", "https://qm.qq.com/q/yaubjC6C5y");
        _openNatayarkPolicyCommand = CreateLinkCommand("Natayark Network 用户协议与隐私政策", "https://account.naids.com/policy");
        _openLobbyPrivacyPolicyCommand = CreateLinkCommand("大厅隐私协议", "https://www.pclc.cc/privacy/personal-info-brief.html");
        _disableGameLinkFeatureCommand = CreateIntentCommand("停用联机功能", "Would disable the PCL CE lobby feature for this launcher profile.");
        _openGameLinkFaqCommand = CreateIntentCommand("常见问题解答", "Would open the P2P 联机常见问题帮助条目.");
        _openEasyTierWebsiteCommand = CreateLinkCommand("EasyTier 工具官网", "https://easytier.cn/");
        _openPysioWebsiteCommand = CreateLinkCommand("Pysio's Home", "https://pysio.online/");
        _selectDownloadFolderCommand = new ActionCommand(SelectDownloadFolder);
        _startCustomDownloadCommand = new ActionCommand(StartCustomDownload);
        _openCustomDownloadFolderCommand = CreateIntentCommand("打开下载文件夹", "Would reveal the selected custom download directory.");
        _saveOfficialSkinCommand = new ActionCommand(SaveOfficialSkin);
        _previewAchievementCommand = new ActionCommand(PreviewAchievement);
        _saveAchievementCommand = CreateIntentCommand("保存成就图片", "Would save the generated achievement preview as an image.");
        _selectHeadSkinCommand = new ActionCommand(SelectHeadSkin);
        _saveHeadCommand = CreateIntentCommand("保存头像", "Would export the generated avatar head image.");
        _resetDownloadInstallSurfaceCommand = new ActionCommand(ResetDownloadInstallSurface);
        _resetDownloadResourceFiltersCommand = new ActionCommand(ResetDownloadResourceFilters);
        _installDownloadResourceModPackCommand = new ActionCommand(InstallDownloadResourceModPack);
        _firstDownloadResourcePageCommand = new ActionCommand(GoToFirstDownloadResourcePage, () => _downloadResourcePageIndex > 0);
        _previousDownloadResourcePageCommand = new ActionCommand(GoToPreviousDownloadResourcePage, () => _downloadResourcePageIndex > 0);
        _nextDownloadResourcePageCommand = new ActionCommand(GoToNextDownloadResourcePage, () => _downloadResourcePageIndex < _downloadResourceTotalPages - 1);
        _manageDownloadFavoriteTargetCommand = CreateIntentCommand("管理收藏夹", "Would open the favorite-target management dialog.");
        _resetInstanceExportOptionsCommand = new ActionCommand(ResetInstanceExportOptions);
        _importInstanceExportConfigCommand = CreateIntentCommand("读取配置", "Would import an instance export configuration file.");
        _saveInstanceExportConfigCommand = CreateIntentCommand("保存配置", "Would save the current instance export configuration to disk.");
        _openInstanceExportGuideCommand = CreateIntentCommand("整合包制作指南", "Would open the instance export guide.");
        _startInstanceExportCommand = new ActionCommand(StartInstanceExport);
        _setLittleSkinCommand = new ActionCommand(() =>
        {
            SelectedInstanceServerLoginRequireIndex = 2;
            InstanceServerAuthServer = "https://littleskin.cn/api/yggdrasil";
            InstanceServerAuthRegister = "https://littleskin.cn/auth/register";
            InstanceServerAuthName = "LittleSkin";
            AddActivity("设置为 LittleSkin", InstanceServerAuthServer);
        });
        _lockInstanceLoginCommand = new ActionCommand(LockInstanceLogin);
        _createInstanceProfileCommand = CreateIntentCommand("新建档案", "Would create a new instance-specific login profile.");
        _openGlobalLaunchSettingsCommand = new ActionCommand(() => NavigateTo(new LauncherFrontendRoute(LauncherFrontendPageKey.Setup, LauncherFrontendSubpageKey.SetupLaunch), "Opened the shared launch settings from instance settings."));

        ScenarioLabel = $"Scenario: {options.Scenario}";
        EnvironmentLabel = _shellComposition.EnvironmentLabel;
        InputLabel = _shellComposition.InputLabel;

        _promptCatalog = BuildPromptCatalog(options.Scenario);
        _allHelpTopics = CreateHelpTopics();
        PropertyChanged += (_, args) => PersistSetupSetting(args.PropertyName);
        PropertyChanged += (_, args) => PersistInstanceSetting(args.PropertyName);
        InitializeAboutEntries();
        InitializeFeedbackSections();
        InitializeToolsGameLinkSurface();
        InitializeToolsTestSurface();
        InitializeDownloadInstallSurface();
        ApplySetupComposition(_setupComposition);
        ApplyInstanceComposition(_instanceComposition);
        InitializePromptLanes();
        RefreshHelpTopics();
        RefreshShell("Shell initialized from portable frontend contracts.");
        if (_currentRoute.Page == LauncherFrontendPageKey.Setup && _currentRoute.Subpage == LauncherFrontendSubpageKey.SetupUpdate)
        {
            _ = CheckForLauncherUpdatesAsync(forceRefresh: false);
        }
    }

}
