using System.Diagnostics;
using System.IO.Compression;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using System.Security.Cryptography;
using PCL.Core.App.Configuration.Storage;

namespace PCL.Frontend.Avalonia.Workflows;

internal static partial class FrontendInstallWorkflowService
{

    private static JsonObject BuildLiteLoaderManifest(FrontendInstallChoice choice)
    {
        if (choice.Metadata?["token"] is not JsonObject token)
        {
            throw new InvalidOperationException("LiteLoader install entry is missing version metadata.");
        }

        var releaseTime = choice.Metadata["releaseTime"]?.GetValue<string>() ?? string.Empty;
        var libraries = token["libraries"] is JsonArray tokenLibraries
            ? (JsonArray)tokenLibraries.DeepClone()
            : new JsonArray();
        libraries.Add(new JsonObject
        {
            ["name"] = $"com.mumfrey:liteloader:{token["version"]?.GetValue<string>() ?? choice.Version}",
            ["url"] = "https://dl.liteloader.com/versions/"
        });

        return new JsonObject
        {
            ["time"] = releaseTime,
            ["releaseTime"] = releaseTime,
            ["type"] = "release",
            ["arguments"] = new JsonObject
            {
                ["game"] = new JsonArray(
                    "--tweakClass",
                    token["tweakClass"]?.GetValue<string>() ?? "com.mumfrey.liteloader.launch.LiteLoaderTweaker")
            },
            ["libraries"] = libraries,
            ["mainClass"] = "net.minecraft.launchwrapper.Launch",
            ["minimumLauncherVersion"] = 18
        };
    }


    private static JsonObject BuildStandaloneOptiFineManifest(
        FrontendInstallApplyRequest request,
        FrontendDownloadProvider downloadProvider,
        Action<string>? onStatusChanged = null,
        FrontendDownloadSpeedLimiter? speedLimiter = null,
        II18nService? i18n = null,
        CancellationToken cancelToken = default)
    {
        var choice = request.OptiFineChoice
                     ?? throw new InvalidOperationException("Missing OptiFine selection.");
        if (IsModernOptiFineVersion(choice))
        {
            return BuildModernOptiFineManifest(request, choice, downloadProvider, onStatusChanged, speedLimiter, i18n, cancelToken);
        }

        return BuildLegacyOptiFineManifest(choice);
    }


    private static JsonObject BuildModernOptiFineManifest(
        FrontendInstallApplyRequest request,
        FrontendInstallChoice choice,
        FrontendDownloadProvider downloadProvider,
        Action<string>? onStatusChanged = null,
        FrontendDownloadSpeedLimiter? speedLimiter = null,
        II18nService? i18n = null,
        CancellationToken cancelToken = default)
    {
        cancelToken.ThrowIfCancellationRequested();
        var installerUrl = choice.DownloadUrl
                           ?? throw new InvalidOperationException("Missing OptiFine download URL.");
        var installerPath = CreateTempFile("pcl-optifine-", ".jar");
        var tempRoot = CreateTempDirectory("pcl-optifine-home-");

        try
        {
            ReportPrepareStatus(onStatusChanged, Text(i18n, "download.install.workflow.tasks.download_optifine_installer", "Downloading the OptiFine installer..."));
            DownloadFileToPath(installerUrl, installerPath, downloadProvider: downloadProvider, speedLimiter: speedLimiter, cancelToken: cancelToken);
            ReportPrepareStatus(
                onStatusChanged,
                Text(
                    i18n,
                    "download.install.workflow.tasks.prepare_vanilla_files",
                    "Preparing vanilla files for Minecraft {version}...",
                    ("version", request.MinecraftChoice.Version)));
            EnsureVanillaVersionFiles(tempRoot, request.MinecraftChoice, downloadProvider, onStatusChanged, speedLimiter, i18n, cancelToken);
            ReportPrepareStatus(onStatusChanged, Text(i18n, "download.install.workflow.tasks.run_optifine_installer", "Running the OptiFine installer..."));
            RunOptiFineInstaller(installerPath, tempRoot, cancelToken);
            ReportPrepareStatus(onStatusChanged, Text(i18n, "download.install.workflow.tasks.copy_optifine_libraries", "Copying libraries generated by OptiFine..."));
            CopyDirectoryContents(Path.Combine(tempRoot, "libraries"), Path.Combine(request.LauncherDirectory, "libraries"));

            var generatedVersion = choice.Metadata?["nameVersion"]?.GetValue<string>();
            if (string.IsNullOrWhiteSpace(generatedVersion))
            {
                throw new InvalidOperationException("OptiFine install entry is missing version directory information.");
            }

            var manifestPath = Path.Combine(tempRoot, "versions", generatedVersion, $"{generatedVersion}.json");
            if (!File.Exists(manifestPath))
            {
                throw new InvalidOperationException("OptiFine installer did not produce a readable version manifest.");
            }

            ReportPrepareStatus(onStatusChanged, Text(i18n, "download.install.workflow.tasks.read_optifine_manifest", "Reading the manifest generated by OptiFine..."));
            return ReadJsonObjectFromFile(manifestPath);
        }
        finally
        {
            TryDeleteFile(installerPath);
            TryDeleteDirectory(tempRoot);
        }
    }


    private static JsonObject BuildLegacyOptiFineManifest(FrontendInstallChoice choice)
    {
        var libraryVersion = choice.Metadata?["libraryVersion"]?.GetValue<string>();
        var downloadUrl = choice.DownloadUrl;
        if (string.IsNullOrWhiteSpace(libraryVersion) || string.IsNullOrWhiteSpace(downloadUrl))
        {
            throw new InvalidOperationException("Legacy OptiFine install entry is missing library information.");
        }

        return new JsonObject
        {
            ["type"] = "release",
            ["libraries"] = new JsonArray
            {
                new JsonObject
                {
                    ["name"] = $"optifine:OptiFine:{libraryVersion}",
                    ["downloads"] = new JsonObject
                    {
                        ["artifact"] = new JsonObject
                        {
                            ["path"] = $"optifine/OptiFine/{libraryVersion}/OptiFine-{libraryVersion}.jar",
                            ["url"] = downloadUrl
                        }
                    }
                },
                new JsonObject
                {
                    ["name"] = "net.minecraft:launchwrapper:1.12"
                }
            },
            ["mainClass"] = "net.minecraft.launchwrapper.Launch",
            ["minimumLauncherVersion"] = "21",
            ["arguments"] = new JsonObject
            {
                ["game"] = new JsonArray("--tweakClass", "optifine.OptiFineTweaker")
            }
        };
    }


    private static void EnsureVanillaVersionFiles(
        string launcherDirectory,
        FrontendInstallChoice minecraftChoice,
        FrontendDownloadProvider downloadProvider,
        Action<string>? onStatusChanged = null,
        FrontendDownloadSpeedLimiter? speedLimiter = null,
        II18nService? i18n = null,
        CancellationToken cancelToken = default)
    {
        cancelToken.ThrowIfCancellationRequested();
        var manifestUrl = minecraftChoice.ManifestUrl
                          ?? throw new InvalidOperationException("Missing Minecraft version manifest URL.");
        ReportPrepareStatus(
            onStatusChanged,
            Text(
                i18n,
                "download.install.workflow.tasks.read_vanilla_version_details",
                "Reading version details for Minecraft {version}...",
                ("version", minecraftChoice.Version)));
        var baseManifest = ReadJsonObject(manifestUrl);
        var versionDirectory = Path.Combine(launcherDirectory, "versions", minecraftChoice.Version);
        Directory.CreateDirectory(versionDirectory);

        var manifestPath = Path.Combine(versionDirectory, $"{minecraftChoice.Version}.json");
        ReportPrepareStatus(
            onStatusChanged,
            Text(
                i18n,
                "download.install.workflow.tasks.write_vanilla_manifest",
                "Writing the vanilla manifest for Minecraft {version}...",
                ("version", minecraftChoice.Version)));
        File.WriteAllText(manifestPath, baseManifest.ToJsonString(JsonNodeOptions), Utf8NoBom);

        var jarPath = Path.Combine(versionDirectory, $"{minecraftChoice.Version}.jar");
        if (File.Exists(jarPath))
        {
            return;
        }

        var clientUrl = baseManifest["downloads"]?["client"]?["url"]?.GetValue<string>();
        if (string.IsNullOrWhiteSpace(clientUrl))
        {
            throw new InvalidOperationException("Missing vanilla client download URL.");
        }

        ReportPrepareStatus(
            onStatusChanged,
            Text(
                i18n,
                "download.install.workflow.tasks.download_vanilla_client",
                "Downloading the vanilla client for Minecraft {version}...",
                ("version", minecraftChoice.Version)));
        DownloadFileToPath(
            clientUrl,
            jarPath,
            baseManifest["downloads"]?["client"]?["sha1"]?.GetValue<string>(),
            downloadProvider,
            speedLimiter,
            cancelToken);
        var launcherProfilesPath = Path.Combine(launcherDirectory, "launcher_profiles.json");
        if (!File.Exists(launcherProfilesPath))
        {
            ReportPrepareStatus(onStatusChanged, Text(i18n, "download.install.workflow.tasks.initialize_launcher_profiles", "Initializing launcher_profiles.json..."));
            File.WriteAllText(launcherProfilesPath, "{}", Utf8NoBom);
        }
    }


    private static void RunOptiFineInstaller(string installerPath, string launcherDirectory, CancellationToken cancelToken = default)
    {
        var javaPath = ResolveJavaExecutable();
        var arguments = $"-Duser.home={QuoteArgument(launcherDirectory)} -cp {QuoteArgument(installerPath)} optifine.Installer";
        if ((GetJavaMajorVersion(javaPath) ?? 0) >= 9)
        {
            arguments = "--add-exports cpw.mods.bootstraplauncher/cpw.mods.bootstraplauncher=ALL-UNNAMED " + arguments;
        }

        RunProcess(javaPath, arguments, launcherDirectory, "OptiFine installer execution failed.", cancelToken);
    }


    private static void RunProcess(string fileName, string arguments, string workingDirectory, string failureMessage, CancellationToken cancelToken = default)
    {
        cancelToken.ThrowIfCancellationRequested();
        var startInfo = new ProcessStartInfo
        {
            FileName = fileName,
            Arguments = arguments,
            WorkingDirectory = workingDirectory,
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true
        };

        using var process = Process.Start(startInfo)
                            ?? throw new InvalidOperationException(failureMessage);
        using var cancellationRegistration = cancelToken.Register(() =>
        {
            try
            {
                if (!process.HasExited)
                {
                    process.Kill(entireProcessTree: true);
                }
            }
            catch
            {
                // Ignore kill failures: the process may have already exited.
            }
        });

        var stdoutTask = process.StandardOutput.ReadToEndAsync();
        var stderrTask = process.StandardError.ReadToEndAsync();
        process.WaitForExit();
        var stdout = stdoutTask.GetAwaiter().GetResult();
        var stderr = stderrTask.GetAwaiter().GetResult();

        cancelToken.ThrowIfCancellationRequested();

        if (process.ExitCode != 0)
        {
            var detail = string.IsNullOrWhiteSpace(stderr) ? stdout : stderr;
            throw new InvalidOperationException($"{failureMessage} {detail}".Trim());
        }
    }


    private static void RunProcess(
        string fileName,
        IReadOnlyList<string> arguments,
        string workingDirectory,
        string failureMessage,
        CancellationToken cancelToken = default)
    {
        cancelToken.ThrowIfCancellationRequested();
        var startInfo = new ProcessStartInfo
        {
            FileName = fileName,
            WorkingDirectory = workingDirectory,
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true
        };

        foreach (var argument in arguments)
        {
            startInfo.ArgumentList.Add(argument);
        }

        using var process = Process.Start(startInfo)
                            ?? throw new InvalidOperationException(failureMessage);
        using var cancellationRegistration = cancelToken.Register(() =>
        {
            try
            {
                if (!process.HasExited)
                {
                    process.Kill(entireProcessTree: true);
                }
            }
            catch
            {
                // Ignore kill failures: the process may have already exited.
            }
        });

        var stdoutTask = process.StandardOutput.ReadToEndAsync();
        var stderrTask = process.StandardError.ReadToEndAsync();
        process.WaitForExit();
        var stdout = stdoutTask.GetAwaiter().GetResult();
        var stderr = stderrTask.GetAwaiter().GetResult();

        cancelToken.ThrowIfCancellationRequested();

        if (process.ExitCode != 0)
        {
            var detail = string.IsNullOrWhiteSpace(stderr) ? stdout : stderr;
            throw new InvalidOperationException($"{failureMessage} {detail}".Trim());
        }
    }


    private static string ResolveJavaExecutable()
    {
        var javaHome = Environment.GetEnvironmentVariable("JAVA_HOME");
        if (!string.IsNullOrWhiteSpace(javaHome))
        {
            var candidate = Path.Combine(javaHome, "bin", OperatingSystem.IsWindows() ? "java.exe" : "java");
            if (File.Exists(candidate))
            {
                return candidate;
            }
        }

        if (!OperatingSystem.IsWindows())
        {
            foreach (var candidate in new[]
                     {
                         "/opt/homebrew/opt/openjdk/bin/java",
                         "/usr/local/opt/openjdk/bin/java"
                     })
            {
                if (File.Exists(candidate))
                {
                    return candidate;
                }
            }
        }

        return OperatingSystem.IsWindows() ? "java.exe" : "java";
    }


    private static int? GetJavaMajorVersion(string javaPath)
    {
        try
        {
            using var process = Process.Start(new ProcessStartInfo
            {
                FileName = javaPath,
                Arguments = "-version",
                UseShellExecute = false,
                RedirectStandardError = true,
                RedirectStandardOutput = true,
                CreateNoWindow = true
            });
            if (process is null)
            {
                return null;
            }

            var output = process.StandardError.ReadToEnd() + process.StandardOutput.ReadToEnd();
            process.WaitForExit();

            var marker = output.IndexOf('"');
            if (marker < 0)
            {
                return null;
            }

            var versionString = output[(marker + 1)..];
            var endMarker = versionString.IndexOf('"');
            if (endMarker >= 0)
            {
                versionString = versionString[..endMarker];
            }

            if (versionString.StartsWith("1.", StringComparison.Ordinal))
            {
                return int.TryParse(versionString.Split('.')[1], out var legacyMajor) ? legacyMajor : null;
            }

            return int.TryParse(versionString.Split('.')[0], out var major) ? major : null;
        }
        catch
        {
            return null;
        }
    }


    private static string QuoteArgument(string value)
    {
        return "\"" + value.Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";
    }


    private static bool IsModernOptiFineVersion(FrontendInstallChoice choice)
    {
        var minecraftVersion = choice.Metadata?["minecraftVersion"]?.GetValue<string>() ?? string.Empty;
        if (minecraftVersion.Contains('w', StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        var parts = minecraftVersion.Split('.', StringSplitOptions.RemoveEmptyEntries);
        return parts.Length >= 2
               && int.TryParse(parts[1], out var minor)
               && minor >= 14;
    }

}
