name: Build And Test

permissions:
  contents: read

on:
  push:
    branches: [dev]
    paths-ignore: &ignored
      - '**/.editorconfig'
      - '**/.gitignore'
      - '**/.gitattributes'
      - '**/*.md'
      - '**/LICENSE'
      - '**/LICENCE'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/FUNDING.yml'
  pull_request:
    paths-ignore: *ignored
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
          - runner: macos-latest
          - runner: windows-latest
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Build Avalonia frontend
        run: dotnet build PCL.Frontend.Avalonia/PCL.Frontend.Avalonia.csproj -c Debug

      - name: Test foundation layer
        run: dotnet test PCL.Core.Backend.Foundation.Test/PCL.Core.Backend.Foundation.Test.csproj -c Debug

      - name: Test backend layer
        run: dotnet test PCL.Core.Backend.Test/PCL.Core.Backend.Test.csproj -c Debug
