name: Build (Reusable)

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
      source_ref:
        required: true
        type: string
      runner:
        required: true
        type: string
      rid:
        required: true
        type: string
      artifact_name:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runner }}
    env:
      LANG: en_US.UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.source_ref }}

      - name: Set Describe
        run: |
          describe=`git describe --tags --always`
          echo "describe=$describe" >> $GITHUB_ENV
          source_sha=`git rev-parse HEAD`
          echo "source_sha=$source_sha" >> $GITHUB_ENV

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Update Help
        continue-on-error: true
        shell: bash
        run: |
          cd ..
          git clone https://github.com/PCL-Community/PCL2CEHelp.git -b master --single-branch --depth 1
          cd PCL2CEHelp
          rm -f ./* || true
          zip -r Help.zip . -x "./.*/*"
          mkdir -p "${{ github.workspace }}/PCL.Frontend.Avalonia/Assets/LauncherAssets/Resources"
          cp -f Help.zip "${{ github.workspace }}/PCL.Frontend.Avalonia/Assets/LauncherAssets/Resources/Help.zip"
          cd ..
          rm -rf PCL2CEHelp
          cd "${{ github.workspace }}"

      - name: Package Frontend
        shell: bash
        env:
          PCL_WRITE_SECRET: '1'
          PCL_MS_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          PCL_CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          PCL_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          PCL_NAID_CLIENT_ID: ${{ secrets.NAID_CLIENT_ID }}
          PCL_NAID_CLIENT_SECRET: ${{ secrets.NAID_CLIENT_SECRET }}
          PCL_LINK_SERVER_ROOT: ${{ secrets.LINK_SERVER_ROOTS }}
          PCL_LOBBY_DEFAULT_SECRET: ${{ secrets.LOBBY_DEFAULT_SECRET }}
          PCL_GITHUB_SHA: ${{ env.source_sha }}
          CONFIGURATION: ${{ inputs.configuration }}
          ARTIFACT_ROOT: ${{ github.workspace }}/artifact
          APP_VERSION: ${{ env.describe }}
        run: |
          chmod +x ./PCL.Frontend.Avalonia/scripts/package-frontend.sh
          ./PCL.Frontend.Avalonia/scripts/package-frontend.sh "${{ inputs.rid }}"

      - name: Upload the Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          if-no-files-found: error
          path: |
            artifact/**/*.zip
            artifact/**/*.tar.gz
